# Generated by Django 5.2.6 on 2025-10-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='Расскажите о себе'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.TextField(blank=True, default='Мой опыт работы:', verbose_name='Опыт работы'),
        ),
    ]
