# Generated by Django 5.2.6 on 2025-10-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_book_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
    ]
