# Generated by Django 5.2.6 on 2025-10-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_person_tour_review_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
    ]
