# Generated by Django 5.2.6 on 2025-10-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_alter_clothes_descriptoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='descriptoin',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt, libero quis laoreet tincidunt, augue risus volutpat ipsum, ut fermentum mauris urna quis nulla. Proin sed ipsum sed justo convallis faucibus. Vivamus viverra, metus ut ullamcorper fringilla, lectus metus dictum purus, ac gravida nisl risus sit amet nisl. Curabitur consequat, mauris at fermentum vulputate, lacus sem gravida turpis, et finibus leo risus iaculis neque. Nullam tincidunt, ipsum sed elementum porttitor, mauris turpis lobortis nisl, sit amet rutrum libero diam id libero. Curabitur blandit erat id odio gravida accumsan. Mauris dolor massa, pharetra vulputate suscipit in, sollicitudin vitae nunc. Morbi fringilla accumsan sapien nec commodo. Ut sit amet est dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec elementum purus et libero condimentum tincidunt. Suspendisse tincidunt eget purus sit amet dapibus. Pellentesque et finibus purus. Praesent accumsan lacus lectus, vel imperdiet turpis imperdiet sed. Maecenas bibendum viverra magna, ac tempor ante rutrum dignissim. ', max_length=2000),
        ),
    ]
