# Generated by Django 5.2.6 on 2025-10-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_alter_clothes_descriptoin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='titles',
            new_name='title',
        ),
    ]
