# Generated by Django 5.2.6 on 2025-10-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_rename_titles_clothes_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='title',
            new_name='titles',
        ),
    ]
