# Generated by Django 5.2.6 on 2025-10-21 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Фильм', max_length=100)),
                ('description', models.TextField(default='Описание фильма00')),
                ('genre', models.CharField(choices=[('Триллер', 'Триллер'), ('Хорор', 'Хоррор'), ('Детектив', 'Детектив')], default='Триллер', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ужастик', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=100, null=True)),
                ('choice_films', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='cineboard.movies')),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='tags',
            field=models.ManyToManyField(to='cineboard.tag'),
        ),
    ]
