# Generated by Django 5.2.6 on 2025-10-09 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0006_rename_review_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название корзины')),
                ('email', models.EmailField(max_length=254, verbose_name='Email пользователя')),
                ('address', models.TextField(blank=True, verbose_name='Адрес доставки')),
            ],
        ),
        migrations.CreateModel(
            name='BuyedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('buying_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='В обработке', verbose_name='Статус заказа')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyed_books', to='basket.basket')),
            ],
            options={
                'verbose_name': 'купленная книга',
                'verbose_name_plural': 'купленные книги',
            },
        ),
    ]
