# Generated by Django 5.2.6 on 2025-10-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_buyedbooks_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyedbooks',
            name='buyer',
        ),
        migrations.AddField(
            model_name='buyedbooks',
            name='buyer_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя покупателя'),
        ),
    ]
